name: Update hanbollar-profile README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this Repository
        uses: actions/checkout@v3

      - name: Get README content
        id: get-readme
        run: echo "::set-output name=readme::$(cat README.md)"

      - name: Checkout the hanbollar-profile default Repository
        uses: actions/checkout@v3
        with:
          repository: hanbollar/hanbollar
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          echo "${{ steps.get-readme.outputs.readme }}" > README.md
          git config user.name "github@hannahbollar.com" #"github-actions[bot]@users.noreply.github.com"
          git config --local user.name "hanbollar" #"github-actions[bot]"
          git add README.md
          git commit -m "Update README"
          git push --quiet --set-upstream origin HEAD
