name: Project List

on:
  push:
  schedule:
    - cron: '3 3 * * 6'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-project-list:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'

    - name: Get Repos
      run: |
        USERNAME="username" # Replace with the username you want to fetch repos for
        REPOS=$(curl -s "https://api.github.com/users/$USERNAME/repos" | jq -r '.[].name + ": " + .[].description')

        echo "repos=$REPOS" >> $GITHUB_ENV

    - name: Use the formatted string
      run: |
        echo "${{ env.repos }}"

    - name: list
      run: |
        echo "${{ env.the_list }}"

    - name: replace old list contents
      run: |
        #substr="<!-- PROJECT LIST_BEGIN -->"
        #substring="<!-- PROJECT LIST_END -->"
        #file="index.html"
 
        #prefix=${str%%$substr*}

        #indexone=${#prefix}
        #echo "indexone"
        #echo $indexone
        #
        #strtwo=$(<$file)
        
        #prefixtwo=${strtwo%%$substring*}

        #indextwo=${#prefixtwo}
        #echo "indextwo"
        #echo $indextwo

        #str_begin=${str:0:indexone}
        #str_end=${str:indextwo:}

        #echo "begin"
        #echo $str_begin
        #echo "end"
        #echo $str_end

        #final="${str_begin}${substr}<br/>${{env.the_list}}<br/>${substring}<br/>${str_end}"
        
        #echo "final"
        #echo $final

        BEGIN_PATTERN="<!-- PROJECT LIST_BEGIN -->"
        END_PATTERN="<!-- PROJECT LIST_END -->"
        sed -i "/$BEGIN_PATTERN/,/$END_PATTERN/c\\
        $BEGIN_PATTERN<br/>${{env.the_list}}<br/>$END_PATTERN
        " index.html

    - name: cat 2
      run: |
        echo "2"
        cat index.html

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v12
      id: verify-changed-files
      with:
        files: index.html

    - name: push changes if any
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "[BOT] all them projects"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
